import { LEADERBOARD_THEME_DEFAULTS } from "@/lib/leaderboard-theme-defaults";

export const DEFAULT_PAGE_THEMES = {
  layout: {
    maxWidth: '1280px',
    padding: '1rem',
    margin: '0 auto',
    containerType: 'max-width',
  },
  header: {
    height: '4rem',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    textColor: '#ffffff',
    isSticky: true,
    showOnScroll: true,
    transparency: 0.5,
  },
} as const;

const defaultLayout = { ...DEFAULT_PAGE_THEMES.layout };
const defaultHeader = { ...DEFAULT_PAGE_THEMES.header };

const defaultFeatures = {
  showJoinCommunity: true,
  showServerRules: true,
  showServers: true,
  showTeam: true,
};

const defaultFeatureSettings = {
  joinCommunity: {
    showDiscord: true,
    showSteam: true,
    showSocialLinks: true,
  },
  serverRules: {
    showCategories: true,
    showLastUpdated: true,
    rules: [] as { title: string; content: string }[],
  },
  team: {
    members: [] as { userId: string; name?: string; image?: string; role?: string; roleColor?: string }[],
  },
};

const pageDefaults: Record<string, Record<string, unknown>> = {
  home: {},
  leaderboard: { ...LEADERBOARD_THEME_DEFAULTS } as Record<string, unknown>,
  servers: {
    backgroundColor: 'hsl(var(--background))',
    cardBackground: 'rgba(255, 255, 255, 0.05)',
    cardBorderRadius: '0.375rem',
    cardShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
    cardHoverEffect: '',
    titleColor: '#ffffff',
    subtitleColor: '#9ca3af',
    categoryTitleColor: '#ffffff',
    categoryTitleSize: '1.5rem',
    statusOnlineColor: '#22c55e',
    statusOfflineColor: '#ef4444',
    wipeTextColor: '#9ca3af',
    progressBarBackground: '#374151',
    progressBarForeground: '#3b82f6',
    progressBarTextColor: '#ffffff',
    playerCountBackground: 'transparent',
    playerCountTextColor: '#ffffff',
    buttonPrimaryBg: '#3b82f6',
    buttonPrimaryText: '#ffffff',
    buttonPrimaryHoverBg: '#2563eb',
    buttonSecondaryBg: 'transparent',
    buttonSecondaryText: '#9ca3af',
    buttonSecondaryBorder: '#374151',
    buttonSecondaryHoverBg: '#374151',
    buttonBorderRadius: '0.375rem',
    rankBadgeBackground: 'rgba(0, 0, 0, 0.7)',
    rankBadgeTextColor: '#ffffff',
    serverImageOverlay: 'rgba(0, 0, 0, 0.3)',
    spacing: '1rem',
    cardPadding: '0.75rem',
  },
  store: {
    layoutPreset: 'default',
    backgroundColor: 'hsl(var(--background))',
    titleColor: 'hsl(var(--foreground))',
    subtitleColor: 'hsl(var(--muted-foreground))',
    categoryCardBackground: 'hsl(var(--card))',
    categoryCardBorder: 'hsl(var(--border))',
    categoryCardHoverBackground: 'hsl(var(--accent))',
    categoryCardTitleColor: 'hsl(var(--foreground))',
    categoryCardHoverTitleColor: 'hsl(var(--accent-foreground))',
    productCardBackground: 'hsl(var(--card))',
    productCardBorder: 'hsl(var(--border))',
    productCardHoverBackground: 'hsl(var(--accent))',
    productCardTitleColor: 'hsl(var(--foreground))',
    productCardDescriptionColor: 'hsl(var(--muted-foreground))',
    productCardPriceColor: 'hsl(var(--foreground))',
    productCardOriginalPriceColor: 'hsl(var(--muted-foreground))',
    productCardDiscountBadgeBackground: 'hsl(var(--primary))',
    productCardDiscountBadgeText: 'hsl(var(--primary-foreground))',
    sidebarBackground: 'hsl(var(--card))',
    sidebarBorder: 'hsl(var(--border))',
    sidebarTitleColor: 'hsl(var(--foreground))',
    sidebarTextColor: 'hsl(var(--muted-foreground))',
    buttonPrimaryBackground: 'hsl(var(--primary))',
    buttonPrimaryText: 'hsl(var(--primary-foreground))',
    buttonPrimaryHoverBackground: 'hsl(var(--primary))',
    buttonSecondaryBackground: 'transparent',
    buttonSecondaryText: 'hsl(var(--foreground))',
    buttonSecondaryBorder: 'hsl(var(--border))',
    buttonSecondaryHoverBackground: 'hsl(var(--accent))',
    buttonBorderRadius: '0.375rem',
    inputBackground: 'hsl(var(--input))',
    inputBorder: 'hsl(var(--border))',
    inputText: 'hsl(var(--foreground))',
    inputPlaceholder: 'hsl(var(--muted-foreground))',
    loadingSpinnerColor: 'hsl(var(--primary))',
    errorTextColor: 'hsl(var(--destructive))',
    successTextColor: 'hsl(var(--primary))',
    blurIntensity: 0,
    cardBorderRadius: '0.375rem',
    cardPadding: '1rem',
    spacing: '1rem',
    cardHoverEffect: '',
  },
  support: {
    backgroundColor: 'hsl(var(--background))',
    titleColor: 'hsl(var(--foreground))',
    subtitleColor: 'hsl(var(--muted-foreground))',
    categoryCardBackground: 'hsl(var(--card))',
    categoryCardBorder: 'hsl(var(--border))',
    categoryCardHoverBackground: 'hsl(var(--accent))',
    categoryCardTitleColor: 'hsl(var(--foreground))',
    categoryCardIconColor: 'hsl(var(--muted-foreground))',
    categoryCardLockColor: 'hsl(var(--muted-foreground))',
    buttonPrimaryBackground: 'hsl(var(--primary))',
    buttonPrimaryText: 'hsl(var(--primary-foreground))',
    buttonPrimaryHoverBackground: 'hsl(var(--primary))',
    buttonSecondaryBackground: 'transparent',
    buttonSecondaryText: 'hsl(var(--foreground))',
    buttonSecondaryBorder: 'hsl(var(--border))',
    buttonSecondaryHoverBackground: 'hsl(var(--accent))',
    buttonBorderRadius: '0.375rem',
    formBackground: 'hsl(var(--card))',
    formBorder: 'hsl(var(--border))',
    inputBackground: 'hsl(var(--input))',
    inputBorder: 'hsl(var(--border))',
    inputText: 'hsl(var(--foreground))',
    inputPlaceholder: 'hsl(var(--muted-foreground))',
    inputFocusBorder: 'hsl(var(--ring))',
    labelColor: 'hsl(var(--foreground))',
    errorTextColor: 'hsl(var(--destructive))',
    successTextColor: 'hsl(var(--primary))',
    warningTextColor: 'hsl(var(--destructive))',
    helpTextColor: 'hsl(var(--muted-foreground))',
    loadingSpinnerColor: 'hsl(var(--primary))',
    banMessageBackground: 'hsl(var(--muted))',
    banMessageBorder: 'hsl(var(--border))',
    banMessageTextColor: 'hsl(var(--foreground))',
    breadcrumbTextColor: 'hsl(var(--muted-foreground))',
    breadcrumbActiveColor: 'hsl(var(--foreground))',
    blurIntensity: 0,
    cardBorderRadius: '0.375rem',
    cardPadding: '1rem',
    spacing: '1rem',
    cardHoverEffect: '',
  },
  maps: {
    backgroundColor: 'hsl(var(--background))',
    titleColor: 'hsl(var(--foreground))',
    subtitleColor: 'hsl(var(--muted-foreground))',
    searchInputBackground: 'hsl(var(--input))',
    searchInputBorder: 'hsl(var(--border))',
    searchInputText: 'hsl(var(--foreground))',
    searchInputPlaceholder: 'hsl(var(--muted-foreground))',
    searchInputFocusBorder: 'hsl(var(--ring))',
    sectionTitleColor: 'hsl(var(--foreground))',
    sectionTitleSize: '1.25rem',
    mapCardBackground: 'hsl(var(--card))',
    mapCardBorder: 'hsl(var(--border))',
    mapCardHoverBackground: 'hsl(var(--accent))',
    mapCardTitleColor: 'hsl(var(--foreground))',
    mapCardServerNameColor: 'hsl(var(--muted-foreground))',
    mapCardStatusTextColor: 'hsl(var(--muted-foreground))',
    mapCardStatusActiveColor: '#22c55e',
    mapCardStatusInactiveColor: '#ef4444',
    mapCardStatusUpcomingColor: '#f59e0b',
    mapCardVoteCountBackground: 'hsl(var(--muted))',
    mapCardVoteCountText: 'hsl(var(--foreground))',
    mapCardBadgeActiveBackground: 'hsl(var(--primary))',
    mapCardBadgeActiveText: 'hsl(var(--primary-foreground))',
    mapCardBadgeSecondaryBackground: 'hsl(var(--muted))',
    mapCardBadgeSecondaryText: 'hsl(var(--foreground))',
    buttonPrimaryBackground: 'hsl(var(--primary))',
    buttonPrimaryText: 'hsl(var(--primary-foreground))',
    buttonPrimaryHoverBackground: 'hsl(var(--primary))',
    buttonSecondaryBackground: 'transparent',
    buttonSecondaryText: 'hsl(var(--foreground))',
    buttonSecondaryBorder: 'hsl(var(--border))',
    buttonSecondaryHoverBackground: 'hsl(var(--accent))',
    buttonBorderRadius: '0.375rem',
    loadingSpinnerColor: 'hsl(var(--primary))',
    loadingSkeletonBackground: 'hsl(var(--muted))',
    errorTextColor: 'hsl(var(--destructive))',
    errorBackground: 'hsl(var(--destructive))',
    errorBorder: 'hsl(var(--border))',
    blurIntensity: 0,
    cardBorderRadius: '0.375rem',
    cardPadding: '1rem',
    cardShadow: '0 1px 3px rgba(0,0,0,0.1)',
    spacing: '1rem',
    cardHoverEffect: '',
  },
  profile: {
    backgroundColor: 'hsl(var(--background))',
    headerCardBackground: 'hsl(var(--card))',
    headerCardBorder: 'hsl(var(--border))',
    avatarBorderColor: 'hsl(var(--border))',
    userNameColor: 'hsl(var(--foreground))',
    userIdColor: 'hsl(var(--muted-foreground))',
    roleBadgeBackground: 'hsl(var(--primary))',
    roleBadgeBorder: 'hsl(var(--border))',
    roleBadgeText: 'hsl(var(--primary-foreground))',
    tabsBackground: 'hsl(var(--card))',
    tabsBorder: 'hsl(var(--border))',
    tabActiveBackground: 'hsl(var(--primary))',
    tabActiveText: 'hsl(var(--primary-foreground))',
    tabInactiveBackground: 'transparent',
    tabInactiveText: 'hsl(var(--muted-foreground))',
    tabHoverBackground: 'hsl(var(--accent))',
    contentCardBackground: 'hsl(var(--card))',
    contentCardBorder: 'hsl(var(--border))',
    contentCardTitleColor: 'hsl(var(--foreground))',
    contentCardDescriptionColor: 'hsl(var(--muted-foreground))',
    connectedAccountSteamBackground: 'hsl(var(--muted))',
    connectedAccountDiscordBackground: 'hsl(var(--muted))',
    connectedAccountIconColor: 'hsl(var(--foreground))',
    connectedAccountTextColor: 'hsl(var(--foreground))',
    connectedAccountStageColor: 'hsl(var(--muted-foreground))',
    buttonPrimaryBackground: 'hsl(var(--primary))',
    buttonPrimaryText: 'hsl(var(--primary-foreground))',
    buttonPrimaryHoverBackground: 'hsl(var(--primary))',
    buttonSecondaryBackground: 'transparent',
    buttonSecondaryText: 'hsl(var(--foreground))',
    buttonSecondaryBorder: 'hsl(var(--border))',
    buttonSecondaryHoverBackground: 'hsl(var(--accent))',
    buttonSuccessBackground: '#22c55e',
    buttonSuccessText: '#ffffff',
    buttonDestructiveBackground: 'hsl(var(--destructive))',
    buttonDestructiveText: 'hsl(var(--destructive-foreground))',
    buttonBorderRadius: '0.375rem',
    copyButtonBackground: 'hsl(var(--muted))',
    copyButtonText: 'hsl(var(--foreground))',
    copyButtonHoverBackground: 'hsl(var(--accent))',
    tableHeaderBackground: 'hsl(var(--muted))',
    tableHeaderText: 'hsl(var(--foreground))',
    tableRowBackground: 'hsl(var(--card))',
    tableRowText: 'hsl(var(--foreground))',
    tableRowHoverBackground: 'hsl(var(--accent))',
    statusActiveColor: '#22c55e',
    statusInactiveColor: '#ef4444',
    statusPendingColor: '#f59e0b',
    linkColor: 'hsl(var(--primary))',
    linkHoverColor: 'hsl(var(--primary))',
    blurIntensity: 0,
    cardBorderRadius: '0.375rem',
    cardPadding: '1rem',
    cardShadow: '0 1px 3px rgba(0,0,0,0.1)',
    spacing: '1rem',
    cardHoverEffect: '',
  },
  bans: {
    backgroundColor: 'hsl(var(--background))',
    titleColor: 'hsl(var(--foreground))',
    subtitleColor: 'hsl(var(--muted-foreground))',
    cardBackground: 'hsl(var(--card))',
    cardBorder: 'hsl(var(--border))',
    cardBorderRadius: '0.375rem',
    cardShadow: '0 1px 3px rgba(0,0,0,0.1)',
    buttonPrimaryBackground: 'hsl(var(--primary))',
    buttonPrimaryText: 'hsl(var(--primary-foreground))',
    buttonPrimaryHoverBackground: 'hsl(var(--primary))',
    buttonSecondaryBackground: 'transparent',
    buttonSecondaryText: 'hsl(var(--foreground))',
    buttonSecondaryBorder: 'hsl(var(--border))',
    buttonSecondaryHoverBackground: 'hsl(var(--accent))',
    buttonBorderRadius: '0.375rem',
    badgeActiveBackground: '#22c55e',
    badgeActiveText: '#ffffff',
    badgeInactiveBackground: '#ef4444',
    badgeInactiveText: '#ffffff',
    badgeGlobalBackground: 'hsl(var(--primary))',
    badgeGlobalText: 'hsl(var(--primary-foreground))',
    badgeCategoryBackground: 'hsl(var(--muted))',
    badgeCategoryText: 'hsl(var(--foreground))',
    badgeIndividualBackground: 'hsl(var(--muted))',
    badgeIndividualText: 'hsl(var(--foreground))',
    textPrimaryColor: 'hsl(var(--foreground))',
    textSecondaryColor: 'hsl(var(--muted-foreground))',
    textMutedColor: 'hsl(var(--muted-foreground))',
    inputBackground: 'hsl(var(--input))',
    inputBorder: 'hsl(var(--border))',
    inputTextColor: 'hsl(var(--foreground))',
    inputPlaceholderColor: 'hsl(var(--muted-foreground))',
    inputBorderRadius: '0.375rem',
    searchBackground: 'hsl(var(--input))',
    searchBorder: 'hsl(var(--border))',
    searchBorderRadius: '0.375rem',
    spacing: '1rem',
    cardPadding: '1rem',
    cardHoverEffect: '',
  },
};

export interface PageThemeFormDefaultValues {
  slug: string;
  enabled: boolean;
  settings: {
    layout: typeof defaultLayout;
    header: typeof defaultHeader;
    [key: string]: unknown;
  };
}

export function getDefaultFormValues(selectedPage?: string): PageThemeFormDefaultValues {
  const settings: PageThemeFormDefaultValues['settings'] = {
    layout: { ...defaultLayout },
    header: { ...defaultHeader },
    features: defaultFeatures,
    featureSettings: defaultFeatureSettings,
  };

  if (selectedPage && pageDefaults[selectedPage]) {
    settings[selectedPage] = { ...pageDefaults[selectedPage] };
  }

  return {
    slug: selectedPage ?? '',
    enabled: true,
    settings,
  };
}
