import { LEADERBOARD_THEME_DEFAULTS } from "@/lib/leaderboard-theme-defaults";
import { STORE_THEME_DEFAULTS } from "@/lib/layout-theme-defaults";
import { HOME_THEME_DEFAULTS } from "@/lib/home-theme-defaults";

export const DEFAULT_PAGE_THEMES = {
  layout: {
    maxWidth: '1280px',
    padding: '1rem',
    margin: '0 auto',
    containerType: 'max-width',
  },
  header: {
    height: '4rem',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    textColor: '#ffffff',
    isSticky: true,
    showOnScroll: true,
    transparency: 0.5,
  },
} as const;

const defaultLayout = { ...DEFAULT_PAGE_THEMES.layout };
const defaultHeader = { ...DEFAULT_PAGE_THEMES.header };

const defaultFeatures = {
  showJoinCommunity: true,
  showServerRules: true,
  showServers: true,
  showTeam: true,
};

const defaultFeatureSettings = {
  joinCommunity: {
    showDiscord: true,
    showSteam: true,
    showSocialLinks: true,
  },
  serverRules: {
    showCategories: true,
    showLastUpdated: true,
    rules: [] as { title: string; content: string }[],
  },
  team: {
    members: [] as { userId: string; name?: string; image?: string; role?: string; roleColor?: string }[],
  },
};

const pageDefaults: Record<string, Record<string, unknown>> = {
  home: { ...HOME_THEME_DEFAULTS } as Record<string, unknown>,
  leaderboard: { ...LEADERBOARD_THEME_DEFAULTS } as Record<string, unknown>,
  servers: {
    backgroundColor: 'hsl(var(--background))',
    cardBackground: 'rgba(255, 255, 255, 0.05)',
    cardBorderRadius: '0.375rem',
    cardShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
    cardHoverEffect: '',
    titleColor: '#ffffff',
    subtitleColor: '#9ca3af',
    categoryTitleColor: '#ffffff',
    categoryTitleSize: '1.5rem',
    statusOnlineColor: '#22c55e',
    statusOfflineColor: '#ef4444',
    wipeTextColor: '#9ca3af',
    progressBarBackground: '#374151',
    progressBarForeground: '#a1a1aa',
    progressBarTextColor: '#ffffff',
    playerCountBackground: 'transparent',
    playerCountTextColor: '#ffffff',
    buttonPrimaryBg: '#52525b',
    buttonPrimaryText: '#ffffff',
    buttonPrimaryHoverBg: '#71717a',
    buttonSecondaryBg: 'transparent',
    buttonSecondaryText: '#9ca3af',
    buttonSecondaryBorder: '#374151',
    buttonSecondaryHoverBg: '#374151',
    buttonBorderRadius: '0.375rem',
    rankBadgeBackground: 'rgba(0, 0, 0, 0.7)',
    rankBadgeTextColor: '#ffffff',
    serverImageOverlay: 'rgba(0, 0, 0, 0.3)',
    spacing: '1rem',
    cardPadding: '0.75rem',
  },
  store: { ...STORE_THEME_DEFAULTS } as Record<string, unknown>,
  support: {
    backgroundColor: 'transparent',
    kickerColor: '#ba9142',
    kickerLabel: 'FAST AND EASY',
    titleColor: '#f2f7ff',
    subtitleColor: '#9facc0',
    pageTitle: 'SUPPORT TICKETS',
    pageSubtitle: 'Choose one of the following options below that best suits you.',
    categoryCardBackground: 'rgba(8, 12, 17, 0.94)',
    categoryCardBorder: 'rgba(72, 97, 125, 0.6)',
    categoryCardHoverBackground: 'rgba(16, 20, 26, 0.98)',
    categoryCardTitleColor: '#eef4fb',
    categoryCardIconColor: '#e1e7ed',
    categoryCardLockColor: '#6b7280',
    categoryCardBodyColor: 'rgba(225, 231, 237, 0.74)',
    categoryCardMetaColor: 'rgba(194, 204, 214, 0.72)',
    openTicketLabel: 'Open ticket',
    buttonPrimaryBackground: '#040609',
    buttonPrimaryText: '#e1e7ed',
    buttonPrimaryHoverBackground: '#10141a',
    buttonSecondaryBackground: 'transparent',
    buttonSecondaryText: '#c5d0de',
    buttonSecondaryBorder: 'rgba(72, 97, 125, 0.6)',
    buttonSecondaryHoverBackground: 'rgba(255, 255, 255, 0.06)',
    buttonBorderRadius: '0px',
    formBackground: 'rgba(16, 17, 22, 0.65)',
    formBorder: 'rgba(72, 97, 125, 0.6)',
    inputBackground: 'rgba(16, 17, 22, 0.65)',
    inputBorder: 'rgba(255, 255, 255, 0.1)',
    inputText: '#eef4fb',
    inputPlaceholder: '#8292a6',
    inputFocusBorder: '#ba9142',
    labelColor: '#eef4fb',
    errorTextColor: '#ef4444',
    successTextColor: '#22c55e',
    warningTextColor: '#f59e0b',
    helpTextColor: '#8292a6',
    loadingSpinnerColor: '#ba9142',
    banMessageBackground: 'rgba(141, 37, 42, 0.16)',
    banMessageBorder: '#8d252a',
    banMessageTextColor: '#eef4fb',
    breadcrumbTextColor: '#8292a6',
    breadcrumbActiveColor: '#eef4fb',
    blurIntensity: 0,
    cardBorderRadius: '0px',
    cardPadding: '20px',
    spacing: '40px',
    cardHoverEffect: '',
  },
  "terms-of-service": {
    accentColor: "#ba9142",
    accentSoft: "#e6c16d",
    accentLink: "#d7b15a",
    titleColor: "#ffffff",
    headingColor: "#edf5ff",
    bodyColor: "#b3c0ce",
    mutedColor: "#8292a6",
    kickerColor: "#ba9142",
    tocLabelColor: "#718398",
    tocInactiveColor: "#718397",
    tocNumberInactiveColor: "#526276",
    introBackground: "rgba(16, 17, 22, 0.65)",
    introBorder: "rgba(186, 145, 66, 0.25)",
    introText:
      "These terms protect fair play, secure purchases, and a respectful environment for every player.",
    lastUpdatedLabel: "LAST UPDATED",
    lastUpdated: "05 August 2026",
    sidebarSupportText: "Questions about these terms?",
  },
  maps: {
    backgroundColor: 'hsl(var(--background))',
    titleColor: 'hsl(var(--foreground))',
    subtitleColor: 'hsl(var(--muted-foreground))',
    searchInputBackground: 'hsl(var(--input))',
    searchInputBorder: 'hsl(var(--border))',
    searchInputText: 'hsl(var(--foreground))',
    searchInputPlaceholder: 'hsl(var(--muted-foreground))',
    searchInputFocusBorder: 'hsl(var(--ring))',
    sectionTitleColor: 'hsl(var(--foreground))',
    sectionTitleSize: '1.25rem',
    mapCardBackground: 'hsl(var(--card))',
    mapCardBorder: 'hsl(var(--border))',
    mapCardHoverBackground: 'hsl(var(--accent))',
    mapCardTitleColor: 'hsl(var(--foreground))',
    mapCardServerNameColor: 'hsl(var(--muted-foreground))',
    mapCardStatusTextColor: 'hsl(var(--muted-foreground))',
    mapCardStatusActiveColor: '#22c55e',
    mapCardStatusInactiveColor: '#ef4444',
    mapCardStatusUpcomingColor: '#f59e0b',
    mapCardVoteCountBackground: 'hsl(var(--muted))',
    mapCardVoteCountText: 'hsl(var(--foreground))',
    mapCardBadgeActiveBackground: 'hsl(var(--primary))',
    mapCardBadgeActiveText: 'hsl(var(--primary-foreground))',
    mapCardBadgeSecondaryBackground: 'hsl(var(--muted))',
    mapCardBadgeSecondaryText: 'hsl(var(--foreground))',
    buttonPrimaryBackground: 'hsl(var(--primary))',
    buttonPrimaryText: 'hsl(var(--primary-foreground))',
    buttonPrimaryHoverBackground: 'hsl(var(--primary))',
    buttonSecondaryBackground: 'transparent',
    buttonSecondaryText: 'hsl(var(--foreground))',
    buttonSecondaryBorder: 'hsl(var(--border))',
    buttonSecondaryHoverBackground: 'hsl(var(--accent))',
    buttonBorderRadius: '0.375rem',
    loadingSpinnerColor: 'hsl(var(--primary))',
    loadingSkeletonBackground: 'hsl(var(--muted))',
    errorTextColor: 'hsl(var(--destructive))',
    errorBackground: 'hsl(var(--destructive))',
    errorBorder: 'hsl(var(--border))',
    blurIntensity: 0,
    cardBorderRadius: '0.375rem',
    cardPadding: '1rem',
    cardShadow: '0 1px 3px rgba(0,0,0,0.1)',
    spacing: '1rem',
    cardHoverEffect: '',
  },
  profile: {
    backgroundColor: 'hsl(var(--background))',
    headerCardBackground: 'hsl(var(--card))',
    headerCardBorder: 'hsl(var(--border))',
    avatarBorderColor: 'hsl(var(--border))',
    userNameColor: 'hsl(var(--foreground))',
    userIdColor: 'hsl(var(--muted-foreground))',
    roleBadgeBackground: 'hsl(var(--primary))',
    roleBadgeBorder: 'hsl(var(--border))',
    roleBadgeText: 'hsl(var(--primary-foreground))',
    tabsBackground: 'hsl(var(--card))',
    tabsBorder: 'hsl(var(--border))',
    tabActiveBackground: 'hsl(var(--primary))',
    tabActiveText: 'hsl(var(--primary-foreground))',
    tabInactiveBackground: 'transparent',
    tabInactiveText: 'hsl(var(--muted-foreground))',
    tabHoverBackground: 'hsl(var(--accent))',
    contentCardBackground: 'hsl(var(--card))',
    contentCardBorder: 'hsl(var(--border))',
    contentCardTitleColor: 'hsl(var(--foreground))',
    contentCardDescriptionColor: 'hsl(var(--muted-foreground))',
    connectedAccountSteamBackground: 'hsl(var(--muted))',
    connectedAccountDiscordBackground: 'hsl(var(--muted))',
    connectedAccountIconColor: 'hsl(var(--foreground))',
    connectedAccountTextColor: 'hsl(var(--foreground))',
    connectedAccountStageColor: 'hsl(var(--muted-foreground))',
    buttonPrimaryBackground: 'hsl(var(--primary))',
    buttonPrimaryText: 'hsl(var(--primary-foreground))',
    buttonPrimaryHoverBackground: 'hsl(var(--primary))',
    buttonSecondaryBackground: 'transparent',
    buttonSecondaryText: 'hsl(var(--foreground))',
    buttonSecondaryBorder: 'hsl(var(--border))',
    buttonSecondaryHoverBackground: 'hsl(var(--accent))',
    buttonSuccessBackground: '#22c55e',
    buttonSuccessText: '#ffffff',
    buttonDestructiveBackground: 'hsl(var(--destructive))',
    buttonDestructiveText: 'hsl(var(--destructive-foreground))',
    buttonBorderRadius: '0.375rem',
    copyButtonBackground: 'hsl(var(--muted))',
    copyButtonText: 'hsl(var(--foreground))',
    copyButtonHoverBackground: 'hsl(var(--accent))',
    tableHeaderBackground: 'hsl(var(--muted))',
    tableHeaderText: 'hsl(var(--foreground))',
    tableRowBackground: 'hsl(var(--card))',
    tableRowText: 'hsl(var(--foreground))',
    tableRowHoverBackground: 'hsl(var(--accent))',
    statusActiveColor: '#22c55e',
    statusInactiveColor: '#ef4444',
    statusPendingColor: '#f59e0b',
    linkColor: 'hsl(var(--primary))',
    linkHoverColor: 'hsl(var(--primary))',
    blurIntensity: 0,
    cardBorderRadius: '0.375rem',
    cardPadding: '1rem',
    cardShadow: '0 1px 3px rgba(0,0,0,0.1)',
    spacing: '1rem',
    cardHoverEffect: '',
  },
  bans: {
    backgroundColor: 'hsl(var(--background))',
    titleColor: 'hsl(var(--foreground))',
    subtitleColor: 'hsl(var(--muted-foreground))',
    cardBackground: 'hsl(var(--card))',
    cardBorder: 'hsl(var(--border))',
    cardBorderRadius: '0.375rem',
    cardShadow: '0 1px 3px rgba(0,0,0,0.1)',
    buttonPrimaryBackground: 'hsl(var(--primary))',
    buttonPrimaryText: 'hsl(var(--primary-foreground))',
    buttonPrimaryHoverBackground: 'hsl(var(--primary))',
    buttonSecondaryBackground: 'transparent',
    buttonSecondaryText: 'hsl(var(--foreground))',
    buttonSecondaryBorder: 'hsl(var(--border))',
    buttonSecondaryHoverBackground: 'hsl(var(--accent))',
    buttonBorderRadius: '0.375rem',
    badgeActiveBackground: '#22c55e',
    badgeActiveText: '#ffffff',
    badgeInactiveBackground: '#ef4444',
    badgeInactiveText: '#ffffff',
    badgeGlobalBackground: 'hsl(var(--primary))',
    badgeGlobalText: 'hsl(var(--primary-foreground))',
    badgeCategoryBackground: 'hsl(var(--muted))',
    badgeCategoryText: 'hsl(var(--foreground))',
    badgeIndividualBackground: 'hsl(var(--muted))',
    badgeIndividualText: 'hsl(var(--foreground))',
    textPrimaryColor: 'hsl(var(--foreground))',
    textSecondaryColor: 'hsl(var(--muted-foreground))',
    textMutedColor: 'hsl(var(--muted-foreground))',
    inputBackground: 'hsl(var(--input))',
    inputBorder: 'hsl(var(--border))',
    inputTextColor: 'hsl(var(--foreground))',
    inputPlaceholderColor: 'hsl(var(--muted-foreground))',
    inputBorderRadius: '0.375rem',
    searchBackground: 'hsl(var(--input))',
    searchBorder: 'hsl(var(--border))',
    searchBorderRadius: '0.375rem',
    spacing: '1rem',
    cardPadding: '1rem',
    cardHoverEffect: '',
  },
};

export interface PageThemeFormDefaultValues {
  slug: string;
  enabled: boolean;
  settings: {
    layout: typeof defaultLayout;
    header: typeof defaultHeader;
    [key: string]: unknown;
  };
}

export function getDefaultFormValues(selectedPage?: string): PageThemeFormDefaultValues {
  const settings: PageThemeFormDefaultValues['settings'] = {
    layout: { ...defaultLayout },
    header: { ...defaultHeader },
    features: defaultFeatures,
    featureSettings: defaultFeatureSettings,
  };

  if (selectedPage && pageDefaults[selectedPage]) {
    settings[selectedPage] = { ...pageDefaults[selectedPage] };
  }

  return {
    slug: selectedPage ?? '',
    enabled: true,
    settings,
  };
}
